version: '3.1'
services: 
  fluentd:
    image: fluentd:${FLUENTD_VERSION:-latest}
    container_name: fluentd
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ${FLUENTD_LOG_VOLUME:-./log}:/fluentd/log:rw
      - ${FLUENTD_CONF_VOLUME:-./etc}:/fluentd/etc:rw
    ports:
      - ${FLUENTD_PORT:-24224}:24224
      - ${FLUENTD_PORT:-24224}:24224/udp
    networks:
      - docker-bridge

# 事先创建好的 docker bridge 网络
networks:
 docker-bridge:
  external: true