version: '3'
services:
  allure:
    image: "frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: NONE
      KEEP_HISTORY: 1
      KEEP_HISTORY_LATEST: 25
    ports:
      - "${ALLURE_DOCKER_SERVICE_PORT:-5050}:5050"
    volumes:
      - ${ALLURE_DOCKER_SERVICE_PROJECTS_VOLUME:-./projects}:/app/projects
    networks:
      - docker-bridge
  allure-ui:
    image: "frankescobar/allure-docker-service-ui"
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://localhost:5050"
      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
    ports:
      - "${ALLURE_DOCKER_WEB_PORT:-5252}:5252"
    networks:
      - docker-bridge

# 事先创建好的 docker bridge 网络
networks:
  docker-bridge:
    external: true

