version: '3.1'
services: 
  ubuntu:
    image: ubuntu:${UBUNTU_VERSION:-latest}
    container_name: ubuntu
    restart: always
    privileged: true
    tty: true
    command: /bin/bash
    volumes:
      - ${UBUNTU_SOURCES_VOLUME:-./sources.list}:/etc/apt/sources.list:rw
      - ${UBUNTU_ROOT_VOLUME:-./root}:/root:rw
    ports:
      - ${UBUNTU_SSH_PORT:-22}:22
    networks:
      - docker-bridge

# 事先创建好的 docker bridge 网络
networks:
 docker-bridge:
  external: true