version: '3.1'
services:
  elasticsearch:
    image: elasticsearch:${ES_VERSION:-latest}
    container_name: elasticsearch
    restart: always
    environment:
      - cluster.name=elasticsearch
      - discovery.type=single-node
      - ES_JAVA_OPTS=${ES_JAVA_OPTS:--Xms512m -Xmx512m}
      - TZ=Asia/Shanghai
    volumes:
      - ${ES_DATA_VOLUME:-./data}:/etc/elasticsearch:rw
      - ${ES_PLUGINS_VOLUME:-./plugins}:/usr/share/elasticsearch/plugins:rw
    ports:
      - ${ES_TCP_PORT:-9300}:9300
      - ${ES_HTTP_PORT:-9200}:9200
    networks:
      - docker-bridge

  kibana:
    image: kibana:${ES_VERSION:-latest}
    container_name: kibana
    restart: always
    environment:
      - I18N_LOCALE=zh-CN
      - TZ=Asia/Shanghai
    ports:
      - ${ES_KIBANA_PORT:-5601}:5601
    depends_on:
      - elasticsearch
    networks:
      - docker-bridge

# 事先创建好的 docker bridge 网络
networks:
  docker-bridge:
    external: true