version: '3.1'
services: 
  influxdb:
    image: influxdb:${INFLUXDB_VERSION:-latest}
    container_name: influxdb
    restart: always
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB:-db0}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER:-admin}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD:-admin}
      - INFLUXDB_GRAPHITE_ENABLED=${INFLUXDB_GRAPHITE_ENABLED:-true}
      - INFLUXDB_USER=${INFLUXDB_USER:-user}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD:-user}
      - TZ=Asia/Shanghai
    volumes:
      - ${INFLUXDB_DATA_VOLUME:-./log}:/var/lib/influxdb:rw
    ports:
      - ${INFLUXDB_HTTP_PORT:-8086}:8086
      - ${INFLUXDB_GRAPHITE_PORT:-2003}:2003
    networks:
      - docker-bridge

# 事先创建好的 docker bridge 网络
networks:
 docker-bridge:
  external: true